version: '3.7'

networks:
  backend_nw:
    driver: bridge
  frontend_nw:
    driver: bridge

services:
  server:
    image: daxart/pychat_server:latest
    container_name: server
    networks:
    - backend_nw

  web:
    image: daxart/pychat_web:latest
    container_name: web
    networks:
    - frontend_nw

  nginx:
    container_name: nginx
    networks:
      - frontend_nw
      - backend_nw
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro