version: '3.3'

networks:
  network:
    driver: bridge

services:
  server:
    image: daxart/pychat_server:latest
    container_name: server
    networks:
    - network
    ports:
    - 127.0.0.1:8080:8080

  web:
    image: daxart/pychat_web:latest
    container_name: web
    networks:
    - network
    ports:
    - 127.0.0.1:80:3000