version: '3'

services:
  server:
    restart: "no"
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server:/opt/pychat/server

  web:
    restart: "no"
    build:
      context: ./web
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./web:/opt/pychat/web
      - /opt/pychat/web/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_HOST=0.0.0.0
