version: '3.7'

services:
  server:
    restart: "no"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/opt/pychat/server
  web:
    restart: "no"
    build:
      context: ./web
      dockerfile: ./dockerfiles/${PC_WEB_BUILD_ENVIRONMENT:-dev}/Dockerfile
    volumes:
      - ./web:/opt/pychat/web
      - /opt/pychat/web/node_modules
    environment:
    - NODE_ENV=development
    - REACT_APP_HOST=0.0.0.0