version: 1

root:
  handlers: [console, file]
  level:    DEBUG

disable_existing_loggers: true

loggers:
  server:
    level: DEBUG
  urllib3:
    level: ERROR
  asyncio:
    level: ERROR

handlers:
  console:
    class:     logging.StreamHandler
    formatter: default
    level:     DEBUG
    stream:    ext://sys.stdout
  file:
    class:     logging.FileHandler
    level:     INFO
    formatter: default
    filename:  info.log
    encoding:  utf8
    mode:      a

formatters:
  default:
    format:  "%(asctime)s %(levelname)-8s [%(name)s::%(filename)s:%(lineno)d] %(message)s"
  brief:
    format:  "[%(levelname)-8s] %(asctime)s '%(name)s': %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
